console.log("==============1==============");
var bankName;
console.log("bank name is:",bankName);
var bankNametypeOf=typeof bankName;
console.log("Datatype of bank name:",bankNametypeOf);
var bankName="SBI bank";
console.log("bank name is:",bankName);
var bankNametypeOf=typeof bankName;
console.log("type of Datatype after initialization:",bankNametypeOf);
console.log("==============2==============");
var marks="90%";
console.log("the mark is:",marks);
var typeofmark=typeof marks;
console.log("the datatype of mark is:",typeofmark);
console.log("==============3==============");
var isWorking;
console.log("the value of isWorking before imitialization:",isWorking);
var isWorkingtype=typeof isWorking;
console.log("the DatatypeisWorking before imitialization:",isWorkingtype);
var isWorking=true;
console.log("the value of isWorking after imitialization:",isWorking);
var isWorkingtype=typeof isWorking;
console.log("the DatatypeisWorking after imitialization:",isWorkingtype);
console.log("==============4==============");
var totalCount="Hundred and Seven";
console.log("value of total count is:",totalCount);
var totalCounttypeof=typeof totalCount;
console.log('the Datatype of totalcountnis:',totalCounttypeof);
var totalCount=107;
console.log("value of total count is:",totalCount);
var totalCounttypeof=typeof totalCount;
console.log('the Datatype of totalcountnis:',totalCounttypeof);

